# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Contour Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:    
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [16.x, 18.x]
    #     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      NEXTAUTH_SECRET: test
      NEXTAUTH_URL: http://localhost:3000
      DISCORD_CLIENT_ID: ""
      DISCORD_CLIENT_SECRET: ""
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: 'npm'
      - name: Installing Dependencies 
        run: npm ci
      - name: Building Application for production
        run: npm run build --if-present
